### ISSUE TITLE
match to CQRS and events systems

### ISSUE THREAD

**Issue by joeblew99** [chrislusf/gleam#2]
There are allot of relationships in Glow and Gleam with CQRS systems.

Have to say this look allot better than Glow. I used glow in a project that was a CQRS architecture.

Why not use some of them same libraries and techniques. Otherwise your reinventing a huge amount of the wheel in the infrastructure layer. The core logic of the flow namespace is great, but for getting distributed computation going, why not just use NATS streaming. It integrates discovery, storage, back pressure, etc etc.
https://github.com/nats-io/nats-streaming-server

just saying...

**Comment by chrislusf** [comment]
I am interested to know your CQRS use case.

The Gleam is more flexible and I have some plans to extend it even further, like adding a SQL layer, smart caching, etc. It's better to write the streaming directly rather than being limited by the existing mostly-working-but-something-does-not-work projects. It will cost more time trying to fit in the shoes.
