### ISSUE TITLE
WriteTo encoding error: msgp: type "map[string][]float64" not supported

### ISSUE THREAD

**Issue by carusyte** [chrislusf/gleam#61]
Every time I update my own project, gleam is updated along with it. My driver program fails to serve request with the following error:
```
2017/09/03 23:22:10 Failed to run task Slices-0: WriteTo encoding error: msgp: type "map[string][]float64" not supported
2017/09/03 23:22:10 Failed to execute on driver side: Failed to send source data: WriteTo encoding error: msgp: type "map[string][]float64" not supported
```
Is there anything changed with the mapper/reducer api?

**Comment by glycerine** [comment]
@carusyte would you kindly post a small reproducible case? @chrislusf asked for my assistance with this, but I can't reproduce.

**Comment by glycerine** [comment]
nevermind, Chris showed me how to repro.

**Comment by chrislusf** [comment]
@carusyte use "map[string][]interface{}" for now. I will keep this open until this is resolved.

**Comment by glycerine** [comment]
I updated greenpack; changing to interface{} should not be needed with the latest. Let me know if you find other issues.

**Comment by chrislusf** [comment]
Thanks to @glycerine for fixing it so quickly!

@carusyte Just update the dependency and you should be good now. No changes needed.
  go get -u github.com/glycerine/greenpack

**Comment by carusyte** [comment]
@glycerine @chrislusf Thank you guys! The fix can be confirmed on my part.

**Comment by carusyte** [comment]
Seems I still have to change my code a little bit though.  I used map[interface{}]interface{} to cast the row slice element type in my mapper `m := row[0].([]interface{})[0].(map[interface{}]interface{})` but I get the following error:
```
interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}
```
Maybe I have to use map[string]interface{} now.
`m := row[0].([]interface{})[0].(map[string]interface{})`
The type inference throughout mapper/reducer is a bit tricky though : )

**Comment by glycerine** [comment]
This touches on some history. The thing is that JSON map keys are required to be strings in the JSON spec. So for JSON compatibility, msgp (the ancestor of greenpack; also produces msgpack, just without version numbers and type clues) only allowed string keys. It does may debugging easier because JSON transform and printing is automatic.

With that backdrop, I'm not sure how big an issue this is (let me know). Another downside is that using interface{} anywhere causes serialization to be slower, of course, because you must fall back upon reflection instead of code generation. Code gen is way way faster.

**Comment by carusyte** [comment]
As long as the approach is proved to be faster (to some degree), I'm willing to sacrifice some readability of my code : ) But I'm not quite sure the performance implication between using maps with keys of `string` and maps with keys of `interface{}`, albeit both value type is `interface{}`.
